// Mock data for the recruitment platform

export const mockCandidates = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    title: "Senior Frontend Engineer",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Node.js"],
    experience: "5 years",
    atsScore: 87,
    cv: {
      name: "Sarah Johnson",
      email: "sarah.johnson@email.com",
      phone: "+1 (555) 123-4567",
      experience: [
        { company: "Tech Corp", position: "Senior Frontend Engineer", duration: "2021-Present" },
        { company: "StartUp Inc", position: "Frontend Engineer", duration: "2019-2021" },
      ],
      education: [{ school: "University of Tech", degree: "BS Computer Science", year: "2019" }],
      skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Node.js", "PostgreSQL", "AWS"],
    },
  },
  {
    id: "2",
    name: "Mike Chen",
    email: "mike.chen@email.com",
    title: "Full Stack Developer",
    skills: ["React", "Node.js", "MongoDB", "AWS", "Docker"],
    experience: "3 years",
    atsScore: 78,
    cv: {
      name: "Mike Chen",
      email: "mike.chen@email.com",
      phone: "+1 (555) 234-5678",
      experience: [
        { company: "Web Services Ltd", position: "Full Stack Developer", duration: "2022-Present" },
        { company: "Digital Agency", position: "Junior Developer", duration: "2020-2022" },
      ],
      education: [{ school: "Tech Institute", degree: "Bootcamp Certification", year: "2020" }],
      skills: ["React", "Node.js", "MongoDB", "AWS", "Docker", "GraphQL", "Jest"],
    },
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@email.com",
    title: "Product Designer",
    skills: ["Figma", "UI/UX Design", "Prototyping", "User Research", "CSS"],
    experience: "4 years",
    atsScore: 92,
    cv: {
      name: "Emily Rodriguez",
      email: "emily.rodriguez@email.com",
      phone: "+1 (555) 345-6789",
      experience: [
        { company: "Design Studio Pro", position: "Senior Product Designer", duration: "2022-Present" },
        { company: "Digital Creative", position: "UI/UX Designer", duration: "2020-2022" },
      ],
      education: [{ school: "Design Academy", degree: "BA Graphic Design", year: "2020" }],
      skills: ["Figma", "Adobe XD", "Prototyping", "User Research", "CSS", "HTML", "Design Systems"],
    },
  },
]

export const mockJobs = [
  {
    id: "1",
    title: "Senior React Developer",
    company: "TechFlow Inc",
    location: "San Francisco, CA",
    workplace: "123 Market Street, Suite 500, San Francisco, CA 94105",
    type: "Full-time",
    position: "Senior Developer",
    salary: "$150,000 - $180,000",
    description: "We are looking for an experienced React developer to lead our frontend team.",
    jobDescription: [
      "Lead frontend development initiatives and mentor junior developers",
      "Design and implement scalable React applications using TypeScript and Next.js",
      "Collaborate with cross-functional teams including product, design, and backend engineers",
      "Optimize application performance and ensure code quality through code reviews",
      "Participate in architectural decisions and technical planning",
      "Stay updated with latest frontend technologies and best practices",
    ],
    requirements: [
      "5+ years of professional experience in React development",
      "Strong proficiency in TypeScript, Next.js, and modern JavaScript",
      "Experience with state management libraries (Redux, Zustand)",
      "Proven leadership skills and ability to mentor team members",
      "Excellent problem-solving and communication skills",
      "Bachelor's degree in Computer Science or related field (preferred)",
    ],
    benefits: [
      "Competitive salary package: $150,000 - $180,000",
      "Comprehensive health, dental, and vision insurance",
      "401(k) retirement plan with company matching",
      "Flexible work hours and remote work options",
      "Professional development budget for courses and conferences",
      "Stock options and performance bonuses",
      "Unlimited paid time off",
      "Modern office in downtown San Francisco with free snacks and beverages",
    ],
    skills: ["React", "TypeScript", "Next.js", "Node.js", "AWS"],
    postedDate: "2025-12-05",
    applicationDeadline: "2026-01-15",
    applicationCount: 42,
    matchedCandidates: 8,
    companyInfo: {
      vision: "To become the leading technology company in fintech solutions, empowering businesses worldwide.",
      mission: "We provide innovative technology solutions that help businesses grow and succeed in the digital age.",
      coreValues: [
        "Innovation: We embrace new technologies and creative solutions",
        "Excellence: We strive for the highest quality in everything we do",
        "Collaboration: We believe in the power of teamwork",
        "Integrity: We conduct business with honesty and transparency",
      ],
      size: "51-200 employees",
      industry: "Technology / Fintech",
      founded: "2018",
    },
  },
  {
    id: "2",
    title: "Full Stack Engineer",
    company: "StartupXYZ",
    location: "Remote",
    workplace: "Remote - Work from anywhere",
    type: "Full-time",
    position: "Mid-level Engineer",
    salary: "$120,000 - $150,000",
    description: "Join our fast-growing team building the future of SaaS.",
    jobDescription: [
      "Develop and maintain full-stack web applications using React and Node.js",
      "Build RESTful APIs and integrate with third-party services",
      "Design and optimize database schemas using PostgreSQL",
      "Implement CI/CD pipelines and deploy applications to cloud infrastructure",
      "Collaborate with product team to define features and technical requirements",
      "Write clean, maintainable code and participate in code reviews",
    ],
    requirements: [
      "3+ years of professional full-stack development experience",
      "Proficiency in React, Node.js, and PostgreSQL",
      "Experience with Git version control and agile development",
      "Strong understanding of RESTful API design",
      "Experience with cloud platforms (AWS, Azure, or GCP)",
      "Excellent communication skills and ability to work independently",
    ],
    benefits: [
      "Competitive salary: $120,000 - $150,000",
      "Fully remote work with flexible hours",
      "Health insurance and dental coverage",
      "Annual learning and development stipend",
      "Home office setup allowance",
      "Quarterly team retreats",
      "Unlimited vacation policy",
      "Stock options package",
    ],
    skills: ["React", "Node.js", "PostgreSQL", "Docker", "AWS"],
    postedDate: "2025-12-04",
    applicationDeadline: "2026-01-10",
    applicationCount: 28,
    matchedCandidates: 12,
    companyInfo: {
      vision: "To revolutionize SaaS solutions and make technology accessible to everyone.",
      mission: "We build innovative SaaS products that help businesses streamline their operations.",
      coreValues: [
        "Customer-first: Our customers' success is our success",
        "Innovation: We constantly push boundaries and explore new possibilities",
        "Work-life balance: We value our team's well-being and personal growth",
      ],
      size: "11-50 employees",
      industry: "SaaS / Technology",
      founded: "2020",
    },
  },
  {
    id: "3",
    title: "Product Designer",
    company: "DesignCo",
    location: "New York, NY",
    workplace: "456 Broadway, 10th Floor, New York, NY 10013",
    type: "Full-time",
    position: "Senior Designer",
    salary: "$110,000 - $140,000",
    description: "Lead product design initiatives for our innovative platform.",
    jobDescription: [
      "Lead design projects from concept to implementation",
      "Create user flows, wireframes, and high-fidelity prototypes in Figma",
      "Conduct user research and usability testing",
      "Collaborate closely with product managers and engineers",
      "Develop and maintain design systems and component libraries",
      "Present design solutions to stakeholders and gather feedback",
    ],
    requirements: [
      "4+ years of product design experience",
      "Expert proficiency in Figma and design tools",
      "Strong portfolio demonstrating UI/UX design skills",
      "Experience with user research methodologies",
      "Excellent visual design and typography skills",
      "Ability to work in a fast-paced, collaborative environment",
    ],
    benefits: [
      "Salary range: $110,000 - $140,000",
      "Health, dental, and vision insurance",
      "401(k) with company match",
      "Flexible PTO and paid holidays",
      "Design conference and workshop budget",
      "Beautiful office in SoHo with design studio",
      "Free lunch and snacks",
      "Commuter benefits",
    ],
    skills: ["Figma", "UI/UX Design", "Prototyping", "User Research", "Design Systems"],
    postedDate: "2025-12-03",
    applicationDeadline: "2026-01-20",
    applicationCount: 35,
    matchedCandidates: 6,
    companyInfo: {
      vision: "To create beautiful, intuitive products that enhance people's lives.",
      mission: "We design digital experiences that users love and businesses need.",
      coreValues: [
        "User-centered design: Users are at the heart of everything we do",
        "Creative excellence: We push creative boundaries and set new standards",
        "Collaboration: Great design comes from great teamwork",
      ],
      size: "26-100 employees",
      industry: "Design / Technology",
      founded: "2019",
    },
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "CloudSys",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$130,000 - $160,000",
    description: "Build and maintain infrastructure for enterprise applications.",
    requirements: ["Docker", "Kubernetes", "AWS", "CI/CD", "3+ years experience"],
    skills: ["Docker", "Kubernetes", "AWS", "Jenkins", "Terraform"],
    postedDate: "2025-12-02",
    applicationCount: 18,
    matchedCandidates: 4,
  },
]

export const mockApplications = [
  {
    id: "1",
    jobId: "1",
    candidateId: "1",
    jobTitle: "Senior React Developer",
    company: "TechFlow Inc",
    status: "interview",
    appliedDate: "2025-12-05",
    atsScore: 87,
    matchScore: 92,
  },
  {
    id: "2",
    jobId: "2",
    candidateId: "1",
    jobTitle: "Full Stack Engineer",
    company: "StartupXYZ",
    status: "applied",
    appliedDate: "2025-12-04",
    atsScore: 87,
    matchScore: 85,
  },
  {
    id: "3",
    jobId: "3",
    candidateId: "2",
    jobTitle: "Product Designer",
    company: "DesignCo",
    status: "rejected",
    appliedDate: "2025-12-03",
    atsScore: 78,
    matchScore: 45,
  },
]

export const mockUsers = [
  { id: "1", name: "Admin User", email: "admin@smartrecruit.com", role: "admin", active: true, joined: "2025-01-01" },
  { id: "2", name: "Sarah Johnson", email: "sarah@example.com", role: "candidate", active: true, joined: "2025-11-15" },
  { id: "3", name: "Mike Chen", email: "mike@example.com", role: "candidate", active: true, joined: "2025-11-20" },
  {
    id: "4",
    name: "John Recruiter",
    email: "john@techflow.com",
    role: "recruiter",
    active: true,
    joined: "2025-11-01",
  },
  {
    id: "5",
    name: "Jane Recruiter",
    email: "jane@startup.com",
    role: "recruiter",
    active: false,
    joined: "2025-10-15",
  },
]

export const mockRanking = [
  {
    candidateId: "1",
    name: "Sarah Johnson",
    matchScore: 92,
    skills: { React: 95, TypeScript: 90, "Next.js": 88, "Node.js": 85, AWS: 80 },
    experience: 5,
    atsScore: 87,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
  },
  {
    candidateId: "2",
    name: "Mike Chen",
    matchScore: 78,
    skills: { React: 85, "Node.js": 90, MongoDB: 88, Docker: 75, AWS: 70 },
    experience: 3,
    atsScore: 78,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
  },
  {
    candidateId: "3",
    name: "Emily Rodriguez",
    matchScore: 65,
    skills: { React: 70, CSS: 85, "UI/UX Design": 90, Prototyping: 88, JavaScript: 60 },
    experience: 4,
    atsScore: 92,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
  },
]

export const mockAdminMetrics = {
  totalUsers: 156,
  totalRecruiterRequests: 45,
  averageMatchScore: 78.5,
  successfulHires: 23,
  platformGrowth: [
    { month: "Sep", users: 45, jobs: 12, applications: 89 },
    { month: "Oct", users: 89, jobs: 28, applications: 156 },
    { month: "Nov", users: 156, jobs: 45, applications: 312 },
    { month: "Dec", users: 234, jobs: 67, applications: 456 },
  ],
}
